### PR TITLE
Pass the host header through to API requests

### PR DESCRIPTION
**Pull request by moddular**

### CODE REVIEW

**Comment by rowanmanning** [comment]
Looks good. Is this technically breaking do you think?

**Comment by rowanmanning** [comment]
And maybe it should be mentioned in the [API Specification](https://github.com/nature/thundermole/blob/master/docs/API-Specification.md) that the host is the original user's host, not the API's host

**Comment by moddular** [comment]
I'll update the API spec

**Comment by rowanmanning** [comment]
Looks great! :shipit: release process is the same as Shunter – update history/package, commit it, tag it, push it, publish it (I added you as a collaborator on npm)

**Comment by rowanmanning** [comment]
> commit it, tag it, push it, publish it
are they lyrics?

**Pull request merged**
